Updating include paths and FEDRA repository
SND-LHC/snddist pull request #35
Opened 2023-11-13 12:43 UTC by antonioiuliano2

Dear all,

Following advice received by @ThomasRuf, I am updating the build information to append the include paths, since the compiler could not find the FEDRA libraries from the CVMFS environment.

I have also updated the repository to the SNDLHC one (instead of my private one), and update the GIT tag number to match the latest SVN revision.

I am available for any comment or question.

Best Regards,
Antonio Iuliano

2023-11-15 19:31 UTC, olantwin requested changes
In my opinion these paths should be set in the FEDRA module file, not the sndsw one.

Also, there is no need to overwrite values you set in the FEDRA recipe in the defaults_release.sh.

2023-11-15 19:33 UTC, olantwin commented
I would also suggest rewriting the git history to make this two commits, one for updating the tags/source repo and one to add the paths to the module.

2023-11-16 14:13 UTC, antonioiuliano2 commented
> In my opinion these paths should be set in the FEDRA module file, not the sndsw one.
> 
> Also, there is no need to overwrite values you set in the FEDRA recipe in the defaults_release.sh.

Since FEDRA modules are not loaded in CVMFS, for now I shall leave the paths in the sndsw.sh script;

So, should I just delete the tag value in the defaults_release, right?

2023-11-16 15:06 UTC, antonioiuliano2 commented
We just confirmed it works with CVMFS. I do not have a local build to test it locally, unfortunately.

2023-11-16 15:09 UTC, ThomasRuf approved these changes
lets try it out

2023-11-16 15:09 UTC, merged